/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayer;

/**
 *
 * @author TEKNO
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NotPlayingPanel = new javax.swing.JPanel();
        notPlayingLabel = new javax.swing.JLabel();
        SongPlayingPanel = new javax.swing.JPanel();
        songThumbLabel = new javax.swing.JLabel();
        songProgressBar = new javax.swing.JProgressBar();
        SeekSongStartButton = new javax.swing.JButton();
        SeekSongEndButton = new javax.swing.JButton();
        PlayPauseButton = new javax.swing.JToggleButton();
        ArtistLabel = new javax.swing.JLabel();
        AlbumNameLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        LikeDislikeButton = new javax.swing.JToggleButton();
        ArtistTextField = new javax.swing.JTextField();
        AlbumNameTextField = new javax.swing.JTextField();
        GenreTextField = new javax.swing.JTextField();
        PodcastPlayingPanel = new javax.swing.JPanel();
        songThumbLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notPlayingLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        notPlayingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notPlayingLabel.setText("NOTHING IS PLAYING");

        javax.swing.GroupLayout NotPlayingPanelLayout = new javax.swing.GroupLayout(NotPlayingPanel);
        NotPlayingPanel.setLayout(NotPlayingPanelLayout);
        NotPlayingPanelLayout.setHorizontalGroup(
            NotPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotPlayingPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(notPlayingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        NotPlayingPanelLayout.setVerticalGroup(
            NotPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NotPlayingPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(notPlayingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel1.add(NotPlayingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 160));

        songThumbLabel.setText("SongThumbnail");

        SeekSongStartButton.setText("<");

        SeekSongEndButton.setText(">");

        PlayPauseButton.setText("PLAY");

        ArtistLabel.setText("Artist:");

        AlbumNameLabel.setText("Album Name:");

        GenreLabel.setText("Genre:");

        LikeDislikeButton.setText("LIKE");

        ArtistTextField.setText("ArtistTextField");

        AlbumNameTextField.setText("AlbumNameTextField");

        GenreTextField.setText("GenreTextField");

        javax.swing.GroupLayout SongPlayingPanelLayout = new javax.swing.GroupLayout(SongPlayingPanel);
        SongPlayingPanel.setLayout(SongPlayingPanelLayout);
        SongPlayingPanelLayout.setHorizontalGroup(
            SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                        .addComponent(songProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SongPlayingPanelLayout.createSequentialGroup()
                        .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                                .addComponent(ArtistLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ArtistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(AlbumNameLabel))
                            .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SeekSongStartButton)
                                .addGap(4, 4, 4)
                                .addComponent(PlayPauseButton)))
                        .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(AlbumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeekSongEndButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LikeDislikeButton)
                                .addGap(110, 110, 110))))))
            .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(songThumbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(692, Short.MAX_VALUE)))
        );
        SongPlayingPanelLayout.setVerticalGroup(
            SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SongPlayingPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArtistLabel)
                    .addComponent(AlbumNameLabel)
                    .addComponent(GenreLabel)
                    .addComponent(ArtistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlbumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeekSongStartButton)
                    .addComponent(SeekSongEndButton)
                    .addComponent(PlayPauseButton)
                    .addComponent(LikeDislikeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(songProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(SongPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SongPlayingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(songThumbLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(SongPlayingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 160));

        songThumbLabel1.setText("PodcastThumbnail");

        javax.swing.GroupLayout PodcastPlayingPanelLayout = new javax.swing.GroupLayout(PodcastPlayingPanel);
        PodcastPlayingPanel.setLayout(PodcastPlayingPanelLayout);
        PodcastPlayingPanelLayout.setHorizontalGroup(
            PodcastPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(PodcastPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PodcastPlayingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(songThumbLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(692, Short.MAX_VALUE)))
        );
        PodcastPlayingPanelLayout.setVerticalGroup(
            PodcastPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(PodcastPlayingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PodcastPlayingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(songThumbLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(PodcastPlayingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlbumNameLabel;
    private javax.swing.JTextField AlbumNameTextField;
    private javax.swing.JLabel ArtistLabel;
    private javax.swing.JTextField ArtistTextField;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JTextField GenreTextField;
    private javax.swing.JToggleButton LikeDislikeButton;
    private javax.swing.JPanel NotPlayingPanel;
    private javax.swing.JToggleButton PlayPauseButton;
    private javax.swing.JPanel PodcastPlayingPanel;
    private javax.swing.JButton SeekSongEndButton;
    private javax.swing.JButton SeekSongStartButton;
    private javax.swing.JPanel SongPlayingPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel notPlayingLabel;
    private javax.swing.JProgressBar songProgressBar;
    private javax.swing.JLabel songThumbLabel;
    private javax.swing.JLabel songThumbLabel1;
    // End of variables declaration//GEN-END:variables
}
